// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.cerebralfix.protobuf.test;

class ChatRequestMessage implements com.cerebralfix.protobuf.Message {
  public function new():Void { }

  // required string message = 1;
  @:fieldNumber(1)
  public var message (default, null) : com.cerebralfix.protobuf.fieldtypes.StringField;
}
