// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.cerebralfix.protobuf.test;

class ChatResponseMessage implements com.cerebralfix.protobuf.Message {
  public function new():Void { }

  // required string username = 1;
  @:fieldNumber(1)
  public var username (default, null) : com.cerebralfix.protobuf.fieldtypes.StringField;

  // required string message = 2;
  @:fieldNumber(2)
  public var message (default, null) : com.cerebralfix.protobuf.fieldtypes.StringField;
}
