// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.cerebralfix.protobuf.test;

class ConnectionResponseMessage implements com.cerebralfix.protobuf.Message {
  public function new():Void { }

  // repeated string usernames = 1;
  @:fieldNumber(1)
  public var usernames:com.cerebralfix.protobuf.fieldtypes.RepeatedField<com.cerebralfix.protobuf.fieldtypes.StringField>;
}
