// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.cerebralfix.protobuf.test;

/**
  	 A message sent by the server in response to the LoginRequestMessage.
 **/
class LoginResponseMessage implements com.cerebralfix.protobuf.Message {

  @:fieldNumber(1)
  /**
    	 True if the user logged in successfully; false if the login failed because the username was already taken.
   **/
  public var logged_in (default, null) : com.cerebralfix.protobuf.fieldtypes.BoolField;

  @:fieldNumber(2)
  /**
    	 The username that the user is now logged in with. Only set if the user logged in successfully.
   **/
  public var username (default, null) : com.cerebralfix.protobuf.fieldtypes.StringField;
  public function new():Void
  {
    logged_in = new com.cerebralfix.protobuf.fieldtypes.BoolField();
    username = new com.cerebralfix.protobuf.fieldtypes.StringField();
  }

}
