// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.cerebralfix.protobuf.test;

class LoginRequestMessage implements com.cerebralfix.protobuf.Message {
  public function new():Void { }

  // required string username = 1;
  @:fieldNumber(1)
  public var username:com.cerebralfix.protobuf.fieldtypes.StringField;
}
