// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.cerebralfix.protobuf.test;

class LoginResponseMessage implements com.cerebralfix.protobuf.Message {
  public function new():Void { }

  // required bool logged_in = 1;
  @:fieldNumber(1)
  public var logged_in:com.cerebralfix.protobuf.fieldtypes.BoolField;

  // optional string username = 2;
  @:fieldNumber(2)
  public var username:com.cerebralfix.protobuf.fieldtypes.StringField;
}
